const ADD_DATE_SUCCESS = 'ADD_DATE_SUCCESS';
const REMOVE_DATE_SUCCESS = 'REMOVE_DATE_SUCCESS';
const ADD_CUSTOMER_SUCCESS = 'ADD_CUSTOMER_SUCCESS';
const REMOVE_CUSTOMER_SUCCESS ='REMOVE_CUSTOMER_SUCCESS';

export {
    ADD_DATE_SUCCESS,
    REMOVE_DATE_SUCCESS,
    ADD_CUSTOMER_SUCCESS,
    REMOVE_CUSTOMER_SUCCESS
}